@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ValidCommand" as ValidCommand LOGIC_COLOR
participant "c:Command" as Command LOGIC_COLOR
end box

[-> LogicManager : execute(someInput)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(someInput)
activate AddressBookParser

activate ValidCommand
AddressBookParser -> ValidCommand: commandTypeOf(commandWord)
ValidCommand --> AddressBookParser: commandType
deactivate ValidCommand

create Command
AddressBookParser -> Command
activate Command

Command --> AddressBookParser:c
deactivate Command

AddressBookParser --> LogicManager : c
deactivate AddressBookParser

LogicManager -> Command : execute()
activate Command

Command --> LogicManager : result
deactivate Command

[<--LogicManager
deactivate LogicManager
@enduml
