@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":IntelliJournalParser" as IntelliJournalParser LOGIC_COLOR
participant ":DeleteContactCommandParser" as DeleteContactCommandParser LOGIC_COLOR
participant "d:DeleteContactCommand" as DeleteContactCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("deletec 1")
activate LogicManager

LogicManager -> IntelliJournalParser : parseCommand("delete 1")
activate IntelliJournalParser

create DeleteContactCommandParser
IntelliJournalParser -> DeleteContactCommandParser
activate DeleteContactCommandParser

DeleteContactCommandParser --> IntelliJournalParser
deactivate DeleteContactCommandParser

IntelliJournalParser -> DeleteContactCommandParser : parse("1")
activate DeleteContactCommandParser

create DeleteContactCommand
DeleteContactCommandParser -> DeleteContactCommand
activate DeleteContactCommand

DeleteContactCommand --> DeleteContactCommandParser : d
deactivate DeleteContactCommand

DeleteContactCommandParser --> IntelliJournalParser : d
deactivate DeleteContactCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteContactCommandParser -[hidden]-> IntelliJournalParser
destroy DeleteContactCommandParser

IntelliJournalParser --> LogicManager : d
deactivate IntelliJournalParser

LogicManager -> DeleteContactCommand : execute()
activate DeleteContactCommand

DeleteContactCommand -> Model : deletePerson(1)
activate Model

Model --> DeleteContactCommand
deactivate Model

create CommandResult
DeleteContactCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteContactCommand
deactivate CommandResult

DeleteContactCommand --> LogicManager : result
deactivate DeleteContactCommand

[<--LogicManager
deactivate LogicManager
@enduml
