@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class AddressBook
Class Journal
Class ReadOnlyAddressBook
Class ReadOnlyJournal
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs
Class AliasMap

Package Person {
Class Person
Class Address
Class Email
Class Name
Class Phone
Class UniquePersonList
}

Package Entry {
Class UniqueEntryList
Class Entry
Class Title
Class Date
Class Description
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up..|> ReadOnlyAddressBook
Journal .up.|> ReadOnlyJournal


ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" AddressBook
ModelManager o-left-> "1" UserPrefs
ModelManager o--> "1" Journal
UserPrefs .up.|> ReadOnlyUserPrefs
ModelManager *--down> AliasMap

AddressBook *--> "1" UniquePersonList
UniquePersonList o--> "*" Person
Person *--> "*" Tag
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address

Journal *--> "1" UniqueEntryList
UniqueEntryList o-> "*" Entry
Entry *--> UniquePersonList
Entry *-----> "*" Tag
Entry *--> Title
Entry *--> Description
Entry *-> Date



Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

ModelManager -->"1" Person : filtered list
ModelManager -->"1" Entry : filtered list
@enduml
