@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface AddressBookStorage <<Interface>>
Interface JournalStorage <<Interface>>
Interface AliasMapStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonAddressBookStorage
Class Storage
Class JsonAdaptedTag


StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o-up-> JournalStorage
StorageManager o--> AddressBookStorage
StorageManager *--> AliasMapStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage

JsonJournalStorage .left.|> JournalStorage
JsonJournalStorage .up.> JsonSerializableJournal
JsonSerializableJournal .right.> JsonAdaptedEntry
JsonAdaptedEntry ....> JsonAdaptedTag
JsonAliasMapStorage ..left> AliasMapStorage

JsonAddressBookStorage .left.|> AddressBookStorage
JsonAddressBookStorage .down.> JsonSerializableAddressBook
JsonSerializableAddressBook .right.> JsonAdaptedPerson
JsonAdaptedPerson .up.> JsonAdaptedTag

@enduml
