@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class PersonListPanel
Class PersonCard
Class ContactContent
Class EntryListPanel
Class EntryCard
Class EntryContent
Class StatusBarFooter
Class CommandBox
Class DashboardTab
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow --> HelpWindow
MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-down-> PersonListPanel
MainWindow *-down-> StatusBarFooter
MainWindow *-down-> EntryListPanel
MainWindow *-down-> EntryContent
MainWindow *-down-> ContactContent
MainWindow *-down-> DashboardTab

DashboardTab -down-> PersonListPanel
PersonListPanel -down-> PersonCard
EntryListPanel -down-> EntryCard
EntryContent ..down.> PersonCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
PersonListPanel --|> UiPart
PersonCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart
EntryListPanel --|> UiPart
EntryCard --|> UiPart
EntryContent --|> UiPart
ContactContent --|> UiPart

PersonCard .right.> Model
EntryCard .right.> Model
UiManager -right-> Logic
MainWindow -left-> Logic

PersonListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
